import { library } from "@fortawesome/fontawesome-svg-core";

// Standard icon imports
import {
    faTimes,
    faCaretLeft,
    faCaretRight,
    faCircle,
    faStore,
    faMoon,
    faSun,
    faDownload,
    faTimesCircle,
    faBars,
    faFileLines,
    faTerminal,
    faCircleExclamation,
    faEarthAmericas,
    faPhone,
    faGlobe,
    faPaperPlane,
    faPlay,
    faSquareCheck,
    faImages,
    faLink,
    faEnvelope,
    faAngleRight,
    faAngleLeft,
    faHome,
    faUser,
    faWalkieTalkie,
    faBriefcase,
    faArrowDown,
    faArrowUp,
    faArrowLeft,
    faArrowRight,
    faArrowDownLong,
    faArrowUpLong,
    faArrowLeftLong,
    faArrowRightLong,
} from "@fortawesome/free-solid-svg-icons";

import {
    faNodeJs,
    faGolang,
    faPython,
    faJs,
    faReact,
    faGitAlt,
    faHtml5,
    faCss3,
    faDocker,
    faJava,
    faLinux,
    faHubspot,
    faUbuntu,
    faConfluence,
} from "@fortawesome/free-brands-svg-icons";

// Branded icon imports
import { faInstagram, faFacebook, faTwitter, faSnapchatGhost, faLinkedin, faGithub } from "@fortawesome/free-brands-svg-icons";

export function loadIcons(){
    library.add(
        faInstagram,
        faLinkedin,
        faGithub,
        faTwitter,
        faFacebook,
        faSnapchatGhost,
        faTimes,
        faCaretLeft,
        faCaretRight,
        faCircle,
        faStore,
        faMoon,
        faSun,
        faDownload,
        faTimesCircle,
        faBars,
        faFileLines,
        faTerminal,
        faCircleExclamation,
        faEarthAmericas,
        faPhone,
        faGlobe,
        faPaperPlane,
        faPlay,
        faSquareCheck,
        faNodeJs,
        faImages,
        faGolang,
        faPython,
        faJs,
        faReact,
        faGitAlt,
        faHtml5,
        faCss3,
        faDocker,
        faJava,
        faLinux,
        faHubspot,
        faUbuntu,
        faConfluence,
        faLink,
        faEnvelope,
        faAngleRight,
        faAngleLeft,
        faWalkieTalkie,
        faBriefcase,
        faUser,
        faHome,
        faArrowDown,
        faArrowUp,
        faArrowLeft,
        faArrowRight,
        faArrowDownLong,
        faArrowUpLong,
        faArrowLeftLong,
        faArrowRightLong,
    );
}
